  
// Configuration: Add/remove repos here easily
const repositories = [
  {
    url: "https://github.com/atsuperman/play2/raw/main/",
    songs: [
{ file: "Poraney Poraney.mp3", details: "🎬 Vaagai Sooda Vaa (2011) / 🎙️ Ranjith, Neha Bhasin / 🎼 Ghibran / 📝 Karthik Netha / 🎥 A. Sarkunam" },
{ file: "Sara Sara Saara Kathu.mp3", details: "🎬 Vaagai Sooda Vaa (2011) / 🎙️ Chinmayi / 🎼 Ghibran / 📝 Vairamuthu / 🎥 A. Sarkunam" },
{ file: "Chinna Chinna Vanna Kuyil.mp3", details: "🎬 Mouna Ragam (1986) / 🎙️ S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali / 🎥 Mani Ratnam" },
{ file: "Mandram Vandha Thendralukku.mp3", details: "🎬 Mouna Ragam (1986) / 🎙️ S. P. Balasubrahmanyam / 🎼 Ilaiyaraaja / 📝 Vaali / 🎥 Mani Ratnam" },
{ file: "Nilaave Vaa.mp3", details: "🎬 Mouna Ragam (1986) / 🎙️ S. P. Balasubrahmanyam / 🎼 Ilaiyaraaja / 📝 Vaali / 🎥 Mani Ratnam" },
{ file: "Oho Megam Vandhadho.mp3", details: "🎬 Mouna Ragam (1986) / 🎙️ S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali / 🎥 Mani Ratnam" },
{ file: "Panivizhum Iravu.mp3", details: "🎬 Mouna Ragam (1986) / 🎙️ S. P. Balasubrahmanyam, S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali / 🎥 Mani Ratnam" },
{ file: "Aattakkari Maman Ponnu.mp3", details: "🎬 Thaarai Thappattai (2016) / 🎙️ M.M. Manasi, Prasanna / 🎼 Ilaiyaraaja / 📝 Ilaiyaraaja / 🎥 Bala" },
{ file: "Anbe Nee yenna.mp3", details: "🎬 Pandiyan (1992) / 🎙️ Mano, K. S. Chithra / 🎼 Ilaiyaraaja / 📝 Vaali / 🎥 SP. Muthuraman" },
{ file: "Paandiyana Kokka.mp3", details: "🎬 Pandiyan (1992) / 🎙️ Mano / 🎼 Ilaiyaraaja / 📝 Vaali / 🎥 SP. Muthuraman" },
{ file: "Paandiyanin Rajayathil.mp3", details: "🎬 Pandiyan (1992) / 🎙️ Mano, K. S. Chithra / 🎼 Karthik Raja / 📝 Panchu Arunachalam / 🎥 S. P. Muthuraman" },
{ file: "Alli Alli.mp3", details: "🎬 Arunachalam (1997) / 🎙️ Mano, Swarnalatha / 🎼 Deva / 📝 Palani Bharathi / 🎥 Sundar C" },
{ file: "Athanda Ithanda.mp3", details: "🎬 Arunachalam (1997) / 🎙️ S. P. Balasubrahmanyam / 🎼 Deva / 📝 Vairamuthu / 🎥 Sundar C" },
{ file: "Mathadu Mathadu.mp3", details: "🎬 Arunachalam (1997) / 🎙️ S. P. Balasubrahmanyam, Sujatha Mohan, Meera, Manorama / 🎼 Deva / 📝 Palani Bharathi / 🎥 Sundar C" },
{ file: "Nagumo.mp3", details: "🎬 Arunachalam (1997) / 🎙️ Hariharan, K. S. Chithra / 🎼 Deva / 📝 Vairamuthu / 🎥 Sundar C" },
{ file: "Singam Ondru.mp3", details: "🎬 Arunachalam (1997) / 🎙️ Malaysia Vasudevan / 🎼 Deva / 📝 Vairamuthu / 🎥 Sundar C" },
{ file: "Kanni Koyil.mp3", details: "🎬 Vaanavil (2000) / 🎙️ S. P. Balasubrahmanyam / 🎼 Deva / 📝 Vairamuthu / 🎥 Manoj Kumar" },
{ file: "Velinattu Kaatru.mp3", details: "🎬 Vaanavil (2000) / 🎙️ Hariharan, Harini / 🎼 Deva / 📝 Vairamuthu / 🎥 Manoj Kumar" },
{ file: "Konja Naal Poru Thalaivaa.mp3", details: "🎬 Aasai (1995) / 🎙️ Hariharan / 🎼 Deva / 📝 Vaali / 🎥 Vasanth" },
{ file: "Meenamma Adikalayilum.mp3", details: "🎬 Aasai (1995) / 🎙️ P. Unnikrishnan, Anuradha Sriram / 🎼 Deva / 📝 Vaali / 🎥 Vasanth" },
{ file: "Pulveli Pulveli.mp3", details: "🎬 Aasai (1995) / 🎙️ K. S. Chithra, P. Unnikrishnan (humming) / 🎼 Deva / 📝 Vairamuthu / 🎥 Vasanth" },
{ file: "Shock Adikuthu.mp3", details: "🎬 Aasai (1995) / 🎙️ Suresh Peters, G. V. Prakash Kumar / 🎼 Deva / 📝 Vaali / 🎥 Vasanth" },
{ file: "Thiloththama.mp3", details: "🎬 Aasai (1995) / 🎙️ S. P. Balasubrahmanyam, Swarnalatha / 🎼 Deva / 📝 Vairamuthu / 🎥 Vasanth" },
{ file: "Innisai Paadi Varum F.mp3", details: "🎬 Thulladha Manamum Thullum (1999) / 🎙️ K. S. Chithra / 🎼 S. A. Rajkumar / 📝 Vairamuthu / 🎥 Ezhil" },
{ file: "Innisai Paadi Varum M.mp3", details: "🎬 Thulladha Manamum Thullum (1999) / 🎙️ P. Unnikrishnan / 🎼 S. A. Rajkumar / 📝 Vairamuthu / 🎥 Ezhil" },
{ file: "Irupathu Kodi Nillavukal.mp3", details: "🎬 Thulladha Manamum Thullum (1999) / 🎙️ Hariharan / 🎼 S. A. Rajkumar / 📝 Vairamuthu / 🎥 Ezhil" },
{ file: "Megamai Vanthu.mp3", details: "🎬 Thulladha Manamum Thullum (1999) / 🎙️ Rajesh Krishnan / 🎼 S. A. Rajkumar / 📝 Muthu Vijayan / 🎥 Ezhil" },
{ file: "Thodu Thodu Enave.mp3", details: "🎬 Thulladha Manamum Thullum (1999) / 🎙️ Hariharan, K. S. Chithra / 🎼 S. A. Rajkumar / 📝 Vairamuthu / 🎥 Ezhil" },
{ file: "Nee Paarthuttu Ponaalum.mp3", details: "🎬 Paarvai Ondre Pothume (2001) / 🎙️ Krishnaraj, Sumithra / 🎼 Bharani / 📝 Bharani / 🎥 Murali Krishna" },
{ file: "Thirudiya Idhayathai.mp3", details: "🎬 Paarvai Ondre Pothume (2001) / 🎙️ Harish Raghavendra, K. S. Chithra / 🎼 Bharani / 📝 Pa. Vijay / 🎥 Murali Krishna" },
{ file: "Thirumba Thirumba.mp3", details: "🎬 Paarvai Ondre Pothume (2001) / 🎙️ P. Unnikrishnan, Harini / 🎼 Bharani / 📝 Pa. Vijay / 🎥 Murali Krishna" },
{ file: "Thuli Thuliyaai Kottum.mp3", details: "🎬 Paarvai Ondre Pothume (2001) / 🎙️ Hariharan, Swarnalatha / 🎼 Bharani / 📝 Pa. Vijay / 🎥 Murali Krishna" },
{ file: "Yeh Asainthadum Katrukkum.mp3", details: "🎬 Paarvai Ondre Pothume (2001) / 🎙️ P. Unnikrishnan, S. Janaki / 🎼 Bharani / 📝 Pa. Vijay / 🎥 Murali Krishna" },
{ file: "Ootha Ootha.mp3", details: "🎬 Minsara Kanna (1999) / 🎙️ Hariharan, Harini / 🎼 Deva / 📝 Vaali / 🎥 K. S. Ravikumar" },
{ file: "Un Paer Solla.mp3", details: "🎬 Minsara Kanna (1999) / 🎙️ Hariharan, Sujatha Mohan / 🎼 Deva / 📝 Kalaikumar / 🎥 K. S. Ravikumar" },
{ file: "Aande Nootrande.mp3", details: "🎬 Mugavaree (2000) / 🎙️ Naveen / 🎼 Deva / 📝 Vairamuthu / 🎥 V. Z. Durai" },
{ file: "Hey Keechu Kiliye F.mp3", details: "🎬 Mugavaree (2000) / 🎙️ Harini, Chorus / 🎼 Deva / 📝 Vairamuthu / 🎥 V. Z. Durai" },
{ file: "Hey Keechu Kiliye M.mp3", details: "🎬 Mugavaree (2000) / 🎙️ Hariharan / 🎼 Deva / 📝 Vairamuthu / 🎥 V. Z. Durai" },
{ file: "Oh Nenje Nenje.mp3", details: "🎬 Mugavaree (2000) / 🎙️ Hariharan, Swarnalatha / 🎼 Deva / 📝 Vairamuthu / 🎥 V. Z. Durai" },
{ file: "Poo Virinchachu.mp3", details: "🎬 Mugavaree (2000) / 🎙️ P. Unnikrishnan, Anuradha Sriram / 🎼 Deva / 📝 Vairamuthu / 🎥 V. Z. Durai" },
{ file: "Yeh Nilave.mp3", details: "🎬 Mugavaree (2000) / 🎙️ Unni Menon / 🎼 Deva / 📝 Vairamuthu / 🎥 V. Z. Durai" },
{ file: "Naan Thamadikira.mp3", details: "🎬 Periyanna (1999) / 🎙️ Vijay / 🎼 Bharani / 📝 Bharani / 🎥 S. A. Chandrasekhar" },
{ file: "Nilave Nilave.mp3", details: "🎬 Periyanna (1999) / 🎙️ Hariharan, Sujatha Mohan / 🎼 Bharani / 📝 Vasan / 🎥 S. A. Chandrasekhar" },
{ file: "Pollachi Malay Rotula.mp3", details: "🎬 Periyanna (1999) / 🎙️ Malaysia Vasudevan, S. N. Surendar, Swarnalatha / 🎼 Bharani / 📝 Pulamaipithan / 🎥 S. A. Chandrasekhar" },
{ file: "Roadtula Oru.mp3", details: "🎬 Periyanna (1999) / 🎙️ Vijay / 🎼 Bharani / 📝 Bharani / 🎥 S. A. Chandrasekhar" },
{ file: "Thannane thamarapoo.mp3", details: "🎬 Periyanna (1999) / 🎙️ S. P. Balasubrahmanyam, K. S. Chithra / 🎼 Bharani / 📝 Arivumathi / 🎥 S. A. Chandrasekhar" },
{ file: "Chingucha Chingucha.mp3", details: "🎬 Porkkaalam (1997) / 🎙️ K. S. Chithra / 🎼 Deva / 📝 Vairamuthu / 🎥 Cheran / 🏷️ Sony Music Entertainment India Pvt. Ltd." },
{ file: "Karuvella Kaatukkulae.mp3", details: "🎬 Porkkaalam (1997) / 🎙️ Arunmozhi, Sujatha Mohan, Anuradha Sriram / 🎼 Deva / 📝 Vairamuthu / 🎥 Cheran / 🏷️ Sony Music Entertainment India Pvt. Ltd." },
{ file: "Oona Oonam.mp3", details: "🎬 Porkkaalam (1997) / 🎙️ Deva, Kovai Kamala / 🎼 Deva / 📝 Vairamuthu / 🎥 Cheran / 🏷️ Sony Music Entertainment India Pvt. Ltd." },
{ file: "Thanjavooru Mannu Eduthu.mp3", details: "🎬 Porkkaalam (1997) / 🎙️ Krishnaraj / 🎼 Deva / 📝 Vairamuthu / 🎥 Cheran / 🏷️ Sony Music Entertainment India Pvt. Ltd." },
{ file: "Iruvathu Vayathuvarai(Duet).mp3", details: "🎬 Kannodu Kanbathellam (1999) / 🎙️ Hariharan, S. Janaki / 🎼 Deva / 📝 Kalai Kumar / 🎥 Prabhu Solomon / 🏷️ Pyramid Music" },
{ file: "Thaj Mahal Ondru.mp3", details: "🎬 Kannodu Kanbathellam (1999) / 🎙️ Hariharan / 🎼 Deva / 📝 Mayil / 🎥 Prabhu Solomon / 🏷️ Pyramid Music" },
{ file: "CBI Enge Theda.mp3", details: "🎬 Poovellam Kettuppar (1999) / 🎙️ Sukhwinder Singh / 🎼 Yuvan Shankar Raja / 📝 Palani Bharathi / 🎥 Vasanth / 🏷️ Sa Re Ga Ma" },
{ file: "Chudithar Aninthu Vantha.mp3", details: "🎬 Poovellam Kettuppar (1999) / 🎙️ Hariharan, Sadhana Sargam / 🎼 Yuvan Shankar Raja / 📝 Palani Bharathi / 🎥 Vasanth / 🏷️ Sa Re Ga Ma" },
{ file: "Irava Pagala.mp3", details: "🎬 Poovellam Kettuppar (1999) / 🎙️ P. Unnikrishnan / 🎼 Yuvan Shankar Raja / 📝 Palani Bharathi / 🎥 Vasanth / 🏷️ Sa Re Ga Ma" },
{ file: "oh Senyoreeta.mp3", details: "🎬 Poovellam Kettuppar (1999) / 🎙️ P. Unnikrishnan / 🎼 Yuvan Shankar Raja / 📝 Palani Bharathi / 🎥 Vasanth / 🏷️ Sa Re Ga Ma" },
{ file: "Poova Poova Poove.mp3", details: "🎬 Poovellam Kettuppar (1999) / 🎙️ Nithyasree Mahadevan / 🎼 Yuvan Shankar Raja / 📝 Palani Bharathi / 🎥 Vasanth / 🏷️ Sa Re Ga Ma" },
{ file: "Poove Poove Male.mp3", details: "🎬 Poovellam Kettuppar (1999) / 🎙️ P. Unnikrishnan / 🎼 Yuvan Shankar Raja / 📝 Palani Bharathi / 🎥 Vasanth / 🏷️ Sa Re Ga Ma" },
{ file: "Aana Aavanna.mp3", details: "🎬 Panchalankurichi (1996) / 🎙️ Krishnaraj, Sujatha / 🎼 Deva / 📝 Vairamuthu / 🎥 Seeman / 🏷️ Pyramid Music" },
{ file: "Aathoram Thopukulae.mp3", details: "🎬 Panchalankurichi (1996) / 🎙️ Swarnalatha / 🎼 Deva / 📝 Vairamuthu / 🎥 Seeman / 🏷️ Pyramid Music" },
{ file: "Chinna Chinna Panithuli.mp3", details: "🎬 Panchalankurichi (1996) / 🎙️ K. S. Chithra / 🎼 Deva / 📝 Vairamuthu / 🎥 Seeman / 🏷️ Pyramid Music" },
{ file: "Othattora Sivappea.mp3", details: "🎬 Panchalankurichi (1996) / 🎙️ Hariharan, Anuradha Sriram / 🎼 Deva / 📝 Vairamuthu / 🎥 Seeman / 🏷️ Pyramid Music" },
{ file: "Vantiyala Vantiyala.mp3", details: "🎬 Panchalankurichi (1996) / 🎙️ Suresh Peters, Anuradha Sriram / 🎼 Deva / 📝 Seeman / 🎥 Seeman / 🏷️ Pyramid Music" },
{ file: "Mazhaiye Mazhaiye.mp3", details: "🎬 Eeram (2009) / 🎙️ Ranjith Govind / 🎼 Thaman S / 📝 Viveka / 🎥 Arivazhagan / 🏷️ Sony Music India" },
{ file: "Tharai Erangiya.mp3", details: "🎬 Eeram (2009) / 🎙️ Suchitra / 🎼 Thaman S / 📝 Viveka / 🎥 Arivazhagan / 🏷️ Sony Music Entertainment India Pvt. Ltd." },
{ file: "Aatha Adikkaiyilae.mp3", details: "🎬 Thenmerku Paruvakaatru (2010) / 🎙️ Harini / 🎼 N. R. Raghunanthan / 📝 Vairamuthu / 🎥 Seenu Ramasamy" },
{ file: "Kalli Kallicheti.mp3", details: "🎬 Thenmerku Paruvakaatru (2010) / 🎙️ Shweta Mohan / 🎼 N. R. Raghunanthan / 📝 Vairamuthu / 🎥 Seenu Ramasamy" },
{ file: "Yedi Kallachi.mp3", details: "🎬 Thenmerku Paruvakaatru (2010) / 🎙️ Vijay Prakash, Shreya Ghoshal / 🎼 N. R. Raghunanthan / 📝 Vairamuthu / 🎥 Seenu Ramasamy" },
{ file: "Ooradangum Samathulae.mp3", details: "🎬 Kalavani (2010) / 🎙️ Senthilvelan / 🎼 S. S. Kumaran / 📝 Na. Muthukumar / 🎥 A. Sarkunam" },
{ file: "Orumurai Irumurai.mp3", details: "🎬 Kalavani (2010) / 🎙️ Harish Raghavendra, Srimathumitha / 🎼 S. S. Kumaran / 📝 Na. Muthukumar / 🎥 A. Sarkunam" },
{ file: "Peancha Mazhai.mp3", details: "🎬 Kalavani (2010) / 🎙️ A. Devendran / 🎼 S. S. Kumaran / 📝 Na. Muthukumar / 🎥 A. Sarkunam" },
{ file: "Sinthaiyiley.mp3", details: "🎬 Kalavani (2010) / 🎙️ Prasanna / 🎼 S. S. Kumaran / 📝 Na. Muthukumar / 🎥 A. Sarkunam" },
{ file: "Machaan Machaan.mp3", details: "🎬 Silambattam (2008) / 🎙️ Ilaiyaraaja, Bela Shende / 🎼 Yuvan Shankar Raja / 📝 Na. Muthukumar / 🎥 S. Saravanan" },
{ file: "Nalamdhana.mp3", details: "🎬 Silambattam (2008) / 🎙️ Silambarasan TR, Earl, Suzi Q, SUVI / 🎼 Yuvan Shankar Raja / 📝 Vaali, Gangai Amaran, Na. Muthukumar, Earl, Suzi Q, Silambarasan TR / 🎥 S. Saravanan" },
{ file: "Tamizhanna Naan Oru.mp3", details: "🎬 Silambattam (2008) / 🎙️ Shankar Mahadevan / 🎼 Yuvan Shankar Raja / 📝 Vaali / 🎥 S. Saravanan" },
{ file: "Vechikkava Remix.mp3", details: "🎬 Silambattam (2008) / 🎙️ Silambarasan Rajendar, Suchitra / 🎼 Yuvan Shankar Raja / 📝 Gangai Amaran / 🎥 S. Saravanan" },
{ file: "Where Is The Party.mp3", details: "🎬 Silambattam (2008) / 🎙️ Mukesh, Priyadharshini / 🎼 Yuvan Shankar Raja / 📝 Silambarasan Rajendar / 🎥 S. Saravanan" },
{ file: "Gaana Karunkuyile.mp3", details: "🎬 Sethu (1999) / 🎙️ Kovai Kamala / 🎼 Ilaiyaraaja / 📝 Ponnadiyan / 🎥 Bala" },
{ file: "Maalai En Vethanai.mp3", details: "🎬 Sethu (1999) / 🎙️ Unni Krishnan, Arunmozhi, S. N. Surendar / 🎼 Ilaiyaraaja / 📝 Arivumathi / 🎥 Bala" },
{ file: "Sikaadha Sitrondru.mp3", details: "🎬 Sethu (1999) / 🎙️ P. Unnikrishnan, Arunmozhi, S. N. Surendar / 🎼 Ilaiyaraaja / 📝 Palani Bharathi / 🎥 Bala" },
{ file: "Vidiya Vidiya.mp3", details: "🎬 Sethu (1999) / 🎙️ P. Unnikrishnan / 🎼 Ilaiyaraaja / 📝 Mu. Metha / 🎥 Bala" },
{ file: "Engengo sellum.mp3", details: "🎬 Pattakkathi Bhairavan (1979) / 🎙️ S. P. Balasubrahmanyam, S. Janaki / 🎼 Ilaiyaraaja / 🎥 V. B. Rajendra Prasad" },
{ file: "Azhagiya Nadhi Enna.mp3", details: "🎬 Paattukku Oru Thalaivan (1989) / 🎙️ S. P. Balasubrahmanyam, K. S. Chithra / 🎼 Ilaiyaraaja / 📝 Gangai Amaran / 🎥 Liaquat Ali Khan" },
{ file: "Kaathalae Kaathalae Duet.mp3", details: "🎬 96 (2018) / 🎙️ Chinmayi, Govind Vasantha / 🎼 Govind Vasantha / 📝 Karthik Netha / 🎥 C. Prem Kumar" },
{ file: "Kaathalae Kaathalae.mp3", details: "🎬 96 (2018) / 🎙️ Kalyani Menon, Chinmayi, Govind Vasantha / 🎼 Govind Vasantha / 📝 Karthik Netha / 🎥 C. Prem Kumar" },
{ file: "Kana Kangiren.mp3", details: "🎬 Aanandha Thaandavam (2009) / 🎙️ Shubha Mudgal, Nithyasree Mahadevan, Vinitra / 🎼 G. V. Prakash Kumar / 📝 Vairamuthu / 🎥 A. R. Gandhi Krishna" },
{ file: "Kodi Aruvi kottuthey.mp3", details: "🎬 Mehandi Circus (2019) / 🎙️ Pradeep Kumar, Nithyashree Venkataramanan / 🎼 Sean Roldan / 📝 Yugabharathi / 🎥 Saravana Rajendran" },
{ file: "The Life Of Ram.mp3", details: "🎬 96 (2018) / 🎙️ Pradeep Kumar / 🎼 Govind Vasantha / 📝 Karthik Netha / 🎥 C. Prem Kumar" },
{ file: "Vellattu Kannazhagi.mp3", details: "🎬 Mehandi Circus (2019) / 🎙️ Sean Roldan / 🎼 Sean Roldan / 📝 Yugabharathi / 🎥 Saravana Rajendran" },
{ file: "Ninaitthathu Yaro.mp3", details: "🎬 Paattukku Oru Thalaivan (1989) / 🎙️ Mano, S. Janaki / 🎼 Ilaiyaraaja / 📝 Gangai Amaran / 🎥 Liaquat Ali Khan" },
{ file: "Kadhal Vennila.mp3", details: "🎬 Vaanathaippola (2000) / 🎙️ Jayachandran / 🎼 S. A. Rajkumar / 📝 Ra. Ravishankar" },
{ file: "Mainave Mainave.mp3", details: "🎬 Vaanathaippola (2000) / 🎙️ Unni Menon, K. S. Chithra / 🎼 S. A. Rajkumar / 📝 Ra. Ravishankar" },
{ file: "Nadhiye Adi Nayil.mp3", details: "🎬 Vaanathaippola (2000) / 🎙️ Sukhwinder Singh, Anuradha Sriram / 🎼 S. A. Rajkumar / 📝 Pa. Vijay" },
{ file: "RojaPoo Malaiyilae.mp3", details: "🎬 Vaanathaippola (2000) / 🎙️ K. S. Chithra, Mano / 🎼 S. A. Rajkumar / 📝 Pa. Vijay" },
{ file: "Thavaniye Ennai.mp3", details: "🎬 Vaanathaippola (2000) / 🎙️ S. P. Balasubrahmanyam, Swarnalatha / 🎼 S. A. Rajkumar / 📝 Pa. Vijay" },
{ file: "Yengal Veetil.mp3", details: "🎬 Vaanathaippola (2000) / 🎙️ S. P. Balasubrahmanyam, Sujatha, Arunmozhi / 🎼 S. A. Rajkumar / 📝 Na. Muthukumar, Pa. Vijay" },
{ file: "Dhavanipotta Deepavali.mp3", details: "🎬 Sandakozhi (2005) / 🎙️ Vijay Yesudas, Shreya Ghoshal / 🎼 Yuvan Shankar Raja / 📝 Yugabharathi" },
{ file: "Kaadhal Neethana.mp3", details: "🎬 Time (1999) / 🎙️ P. Unnikrishnan, Sujatha Mohan / 🎼 Ilaiyaraaja / 📝 Palani Bharathi" },
{ file: "Ketta Kodukkira Boomi.mp3", details: "🎬 Sandakozhi (2005) / 🎙️ Jassie Gift, Sujatha Mohan, Chinmayi Sripaada, Ganga / 🎼 Yuvan Shankar Raja / 📝 Thamarai" },
{ file: "Muthu Nilavae.mp3", details: "🎬 Time (1999) / 🎙️ Karthik Raja, Gopika Poornima / 🎼 Ilaiyaraaja / 📝 Palani Bharathi" },
{ file: "Thavikiren.mp3", details: "🎬 Time (1999) / 🎙️ Hariharan, Bhavatharini / 🎼 Ilaiyaraaja / 📝 Palani Bharathi" },
{ file: "Cho Larey.mp3", details: "🎬 Ullaasam (1997) / 🎙️ S. P. Balasubrahmanyam, Harini, Venkat Prabhu / 🎼 Karthik Raja / 📝 Paarthi Bhaskar" },
{ file: "Konjum Manjal.mp3", details: "🎬 Ullaasam (1997) / 🎙️ Hariharan, Harini / 🎼 Karthik Raja / 📝 Palani Bharathi" },
{ file: "Muthae Muthamma.mp3", details: "🎬 Ullaasam (1997) / 🎙️ Kamal Haasan, Bhavatharini, Swarnalatha / 🎼 Karthik Raja / 📝 Palani Bharathi" },
{ file: "Veesum Kaatrukku.mp3", details: "🎬 Ullaasam (1997) / 🎙️ P. Unnikrishnan, Harini / 🎼 Karthik Raja / 📝 Palani Bharathi" },
{ file: "Yaaro Yaar Yaaro.mp3", details: "🎬 Ullaasam (1997) / 🎙️ Ilaiyaraaja, Bhavatharini / 🎼 Karthik Raja / 📝 Arivumathi" },
{ file: "Aalaala Kandaa.mp3", details: "🎬 Sangamam (1999) / 🎙️ Hariharan, M. S. Viswanathan / 🎼 A. R. Rahman / 📝 Vairamuthu" },
{ file: "Margazhi Thingal.mp3", details: "🎬 Sangamam (1999) / 🎙️ P. Unnikrishnan, S. Janaki, A. R. Rahman, Srimathumitha / 🎼 A. R. Rahman / 📝 Vairamuthu" },
{ file: "Mazhaithuli Mazhaithuli.mp3", details: "🎬 Sangamam (1999) / 🎙️ Hariharan, M. S. Viswanathan / 🎼 A. R. Rahman / 📝 Vairamuthu" },
{ file: "Mudhal Murai.mp3", details: "🎬 Sangamam (1999) / 🎙️ Srinivas, Sujatha Mohan / 🎼 A. R. Rahman / 📝 Vairamuthu" },
{ file: "Sowkiyama Kanne.mp3", details: "🎬 Sangamam (1999) / 🎙️ Nithyasree Mahadevan / 🎼 A. R. Rahman / 📝 Vairamuthu" },
{ file: "Varaha Nadikkarai Oram.mp3", details: "🎬 Sangamam (1999) / 🎙️ Shankar Mahadevan / 🎼 A. R. Rahman / 📝 Vairamuthu" },
{ file: "En Nenjee.mp3", details: "🎬 Vamsam (2010) / 🎙️ Ananthu, Priyadharshini / 🎼 Taj Noor / 📝 Na. Muthukumar" },
{ file: "Kompula Poove Suthi.mp3", details: "🎬 Virumaandi (2004) / 🎙️ Kamal Haasan / 🎼 Ilaiyaraaja / 📝 Kamal Haasan" },
{ file: "Maruthani Poova Pola.mp3", details: "🎬 Vamsam (2010) / 🎙️ Mukesh, Surmukhi / 🎼 Taj Noor / 📝 Na. Muthukumar" },
{ file: "Unnaivida.mp3", details: "🎬 Virumaandi (2004) / 🎙️ Kamal Haasan, Shreya Ghoshal / 🎼 Ilaiyaraaja / 📝 Kamal Haasan" },
{ file: "katthavaraya.mp3", details: "🎬 Kavithai (1976) / 🎙️ Malathi,  Sabesh / 🎼 Deva" },
{ file: "Kotha Raja.mp3", details: "🎬 King of Kotha (2023) / 🎙️ Asal Kolaar, Dabzee, Roll Rida, Resmi Sateesh / 🎼 Jakes Bejoy / 📝 Mu.Ri" },
{ file: "Oru Kola Kili.mp3", details: "🎬 Uzhaippali (1993) / 🎙️ S. P. Balasubrahmanyam / 🎼 Ilaiyaraaja / 📝 Vaali" },
{ file: "Oru Maina.mp3", details: "🎬 Uzhaippali (1993) / 🎙️ Mano, K. S. Chithra / 🎼 Ilaiyaraaja / 📝 Vaali" },
{ file: "Umma Ummamaa.mp3", details: "🎬 Adithadi (2004) / 🎙️ Malathi, Manikka Vinayagam / 🎼 Deva" },
{ file: "Uzhaippali illatha.mp3", details: "🎬 Uzhaippali (1993) / 🎙️ Mano / 🎼 Ilaiyaraaja / 📝 Vaali" },
{ file: "Annan Adhiradi.mp3", details: "🎬 Leo Promo Track (2023) / 🎙️ Tha Mystro, MC SAI / 🎼 MJ Melodies / 📝 Tha Mystro, MC SAI / 🎥 Saanmuu" },
{ file: "Hey Saloma.mp3", details: "🎬 Subash (1996) / 🎙️ Vidyasagar, Swarnalatha / 🎼 Vidyasagar / 📝 R. V. Udayakumar" },
{ file: "Sudum Nilavu.mp3", details: "🎬 Thambi (2006) / 🎙️ P. Unnikrishnan, Harini / 🎼 Vidyasagar / 📝 Vairamuthu" },
{ file: "Summa Kidantha.mp3", details: "🎬 Thambi (2006) / 🎙️ Karthik, Kalyani Nair / 🎼 Vidyasagar / 📝 Vairamuthu" },
{ file: "Balle Lakka.mp3", details: "🎬 Mankatha (2011) / 🎙️ Karthik, Vijay Yesudas, Anusha Dhayanidhi / 🎼 Yuvan Shankar Raja / 📝 Vaali" },
{ file: "January Madham.mp3", details: "🎬 7G Rainbow Colony (2004) / 🎙️ Mathangi Jagdish, Kunal Ganjawala / 🎼 Yuvan Shankar Raja / 📝 Na. Muthukumar" },
{ file: "Machi Open The Bottle.mp3", details: "🎬 Mankatha (2011) / 🎙️ Mano, Haricharan, Tippu, Naveen Madhav / 🎼 Yuvan Shankar Raja / 📝 Vaali" },
{ file: "Mangatha Extended Dance.mp3", details: "🎬 Mankatha (2011) / 🎙️ Yuvan Shankar Raja, Ranjith, Premgi Amaren, Sucharita, Anitha / 🎼 Yuvan Shankar Raja / 📝 Gangai Amaren, Sucharita, Yuvan Shankar Raja" },
{ file: "Vaada Bin Laada.mp3", details: "🎬 Mankatha (2011) / 🎙️ Krish, Suchitra / 🎼 Yuvan Shankar Raja / 📝 Vaali" },
{ file: "Vilayadu Mangatha.mp3", details: "🎬 Mankatha (2011) / 🎙️ Yuvan Shankar Raja, Ranjith, Premgi Amaren, Sucharita, Anitha / 🎼 Yuvan Shankar Raja / 📝 Gangai Amaren, Sucharita, Yuvan Shankar Raja" },
{ file: "Asku Maaro.mp3", details: "💽 Independent Single (2021) / 🎙️ Dharan Kumar, Sivaangi Krishnakumar / 🎼 Dharan Kumar / 📝 Dharan Kumar" },
{ file: "Bae.mp3", details: "🎬 Don (2022) / 🎙️ Adithya RK / 🎼 Anirudh Ravichander / 📝 Vignesh Shivan" },
{ file: "Jalabulajangu.mp3", details: "🎬 Don (2022) / 🎙️ Anirudh Ravichander / 🎼 Anirudh Ravichander / 📝 Rokesh" },
{ file: "Private Party.mp3", details: "🎬 Don (2022) / 🎙️ Anirudh Ravichander, Jonita Gandhi / 🎼 Anirudh Ravichander / 📝 Sivakarthikeyan" },
{ file: "Anaarkali.mp3", details: "🎬 Varushamellam Vasantham (2002) / 🎙️ P. Unnikrishnan, Ganga Sitharasu / 🎼 Sirpy / 📝 Ra. Ravishankar" },
{ file: "Enge andha vennila.mp3", details: "🎬 Varushamellam Vasantham (2002) / 🎙️ Unni Menon / 🎼 Sirpy / 📝 Ra. Ravishankar" },
{ file: "Enge Antha Vennila Female.mp3", details: "🎬 Varushamellam Vasantham (2002) / 🎙️ Sujatha Mohan / 🎼 Sirpy / 📝 Ra. Ravishankar" },
{ file: "Muthal muthalai unai.mp3", details: "🎬 Varushamellam Vasantham (2002) / 🎙️ P. Unnikrishnan, Sujatha Mohan / 🎼 Sirpy / 📝 Ra. Ravishankar" },
{ file: "Naan ready Neenga.mp3", details: "🎬 Varushamellam Vasantham (2002) / 🎙️ Krishnaraj, K. S. Chithra / 🎼 Sirpy / 📝 Manavai Ponmanikkam" },
{ file: "Erukanchedi ooram.mp3", details: "🎬 Santhaikku Vantha Kili (1995) / 🎙️ S. Janaki / 🎼 Deva / 📝 Vaali" },
{ file: "oothikka mama.mp3", details: "🎬 Santhaikku Vantha Kili (1995) / 🎙️ S. Janaki / 🎼 Deva / 📝 Vaali" },
{ file: "Poththu Athai.mp3", details: "🎬 Kadhal Kirukkan (2003) / 🎙️ Manikka Vinayagam, Malathy / 🎼 Deva / 📝 Deva Kumar" },
{ file: "Poove Muthal Poove.mp3", details: "🎬 Kadhal Kirukkan (2003) / 🎙️ Harish Raghavendra / 🎼 Deva / 📝 Kabilan" },
{ file: "Poove Mudhal poove female.mp3", details: "🎬 Kadhal Kirukkan (2003) / 🎙️ Chinmayi Sripada / 🎼 Deva / 📝 Kabilan" },
{ file: "Aattama TherottamaMix.mp3", details: "🎬 Singakutty (2008) / 🎙️ Anuradha Sriram, DJ Ewan / 🎼 Prasanna Shekhar / 📝 Vaali" },
{ file: "Aalana Naal Mudhala.mp3", details: "🎬 Kaadhal Kavithai (1998) / 🎙️ Pushpavanam Kuppusamy, Sowmya Raoh / 🎼 Ilaiyaraaja / 📝 Agathiyan" },
{ file: "Thath Thom thakdheemi.mp3", details: "🎬 Kaadhal Kavithai (1998) / 🎙️ Ila Arun, Swarnalatha / 🎼 Ilaiyaraaja / 📝 Agathiyan" },
{ file: "Oru Naalil Dream Mix.mp3", details: "🎬 Pudhupettai (2006) / 🎙️ Yuvan Shankar Raja / 🎼 Yuvan Shankar Raja / 📝 Na. Muthukumar" },
{ file: "Oru Naalil.mp3", details: "🎬 Pudhupettai (2006) / 🎙️ Yuvan Shankar Raja / 🎼 Yuvan Shankar Raja / 📝 Na. Muthukumar" },
{ file: "Pulpesum Poo Pesum.mp3", details: "🎬 Pudhupettai (2006) / 🎙️ Vijay Yesudas, Tanvi Shah, Premji Amaran, Yuvan Shankar Raja / 🎼 Yuvan Shankar Raja / 📝 Na. Muthukumar" },
{ file: "Appan Panna Thappula.mp3", details: "🎬 Thirupaachi (2005) / 🎙️ Pushpavanam Kuppusamy, Anuradha Sriram / 🎼 Dhina / 📝 Perarasu" },
{ file: "Kannum Kannumthan.mp3", details: "🎬 Thirupaachi (2005) / 🎙️ Harish Raghavendra, Uma Ramanan, Premji Amaren / 🎼 Mani Sharma / 📝 Perarasu" },
{ file: "Kattu Kattu.mp3", details: "🎬 Thirupaachi (2005) / 🎙️ Manikka Vinayagam, Sumangali / 🎼 Devi Sri Prasad / 📝 Perarasu" },
{ file: "Kumbida Pona deivam.mp3", details: "🎬 Thirupaachi (2005) / 🎙️ Shankar Mahadevan, Malathy Lakshman / 🎼 Dhina / 📝 Perarasu" },
{ file: "Nee Entha Ooru.mp3", details: "🎬 Thirupaachi (2005) / 🎙️ Tippu / 🎼 Dhina / 📝 Perarasu" },
{ file: "Adho Varaa.mp3", details: "🎬 Sullan (2004) / 🎙️ Pushpavanam Kuppusamy, Harini / 🎼 Vidyasagar / 📝 Pa. Vijay" },
{ file: "Thottu Thottu.mp3", details: "🎬 Ethirum Puthirum (1999) / 🎙️ Swarnalatha, Pushpavanam Kuppusamy / 🎼 Vidyasagar / 📝 Vairamuthu" },
{ file: "Kaathu Pasapasanga.mp3", details: "🎬 Ethirum Puthirum (1999) / 🎙️ Pushpavanam Kuppusamy, Malaysia Vasudevan, Anuradha Sriram, Gopal Rao / 🎼 Vidyasagar / 📝 Vairamuthu" },
{ file: "Potteduthu vachuvidava.mp3", details: "🎬 Style (2002) / 🎙️ Pushpavanam Kuppusamy, Swarnalatha / 🎼 Bharani / 📝 Pa. Vijay" },
{ file: "Thom Thom.mp3", details: "🎬 Alli Thandha Vaanam (2001) / 🎙️ Hariharan, K. S. Chithra / 🎼 Vidyasagar" },
{ file: "Vadi Vadi Nattukkattai.mp3", details: "🎬 Alli Thandha Vaanam (2001) / 🎙️ Shankar Mahadevan, Sujatha Mohan / 🎼 Vidyasagar" },
{ file: "Bothai yeri pochu.mp3", details: "🎬 Jai Hind (1994) / 🎙️ S. P. Sailaja, Suresh Peters / 🎼 Vidyasagar / 📝 Vairamuthu" },
{ file: "Kanna En Selaikulla.mp3", details: "🎬 Jai Hind (1994) / 🎙️ S. P. Balasubrahmanyam, S. Janaki / 🎼 Vidyasagar / 📝 Vairamuthu" },
{ file: "Mutham thara.mp3", details: "🎬 Jai Hind (1994) / 🎙️ Mano, Sindhu / 🎼 Vidyasagar / 📝 Vairamuthu" },
{ file: "Thanni Vachu.mp3", details: "🎬 Jai Hind (1994) / 🎙️ Arjun, Malgudi Shubha, Vidyasagar / 🎼 Vidyasagar / 📝 Vairamuthu" },
{ file: "Katchi Sera.mp3", details: "💿 Think Indie (2024) / 🎙️ Sai Abhyankar / 🎼 Sai Abhyankar / 📝 Adesh Krishna" },
{ file: "Ordinary Person.mp3", details: "🎬 Leo (2023) / 🎙️ Anirudh Ravichander, Nikhita Gandhi / 🎼 Anirudh Ravichander / 📝 Heisenberg" },
{ file: "Kannathil Kannam.mp3", details: "🎬 Watchman Vadivel (1994) / 🎙️ S. P. Balasubrahmanyam, K. S. Chithra / 🎼 Deva / 📝 Vaali" },
{ file: "Chandiranum Sooriyanum.mp3", details: "🎬 Watchman Vadivel (1994) / 🎙️ S. P. Balasubrahmanyam, K. S. Chithra / 🎼 Deva / 📝 Vaali" },
{ file: "tamil_iragai_pole_clup_mix_tape.mp3", details: "Remix By dj jose" },
{ file: "Kissik.mp3", details: "🎬 Pushpa 2: The Rule (2024) / 🎙️ Sreeleela / 🎼 Devi Sri Prasad / 📝 Chandrabose" },
{ file: "Pushpa Pushpa.mp3", details: "🎬 Pushpa 2: The Rule (2024) / 🎙️ Nakash Aziz / 🎼 Devi Sri Prasad / 📝 Chandrabose" },
{ file: "Kavalaiyai Theerpadhu Naatiya.mp3", details: "🎬 Sivakavi (1943) / 🎙️ M. K. Thyagaraja Bhagavathar / 🎼 Papanasam Sivan / 📝 Papanasam Sivan" },
{ file: "Soppana Vaazhvil.mp3", details: "🎬 Sivakavi (1943) / 🎙️ M. K. Thyagaraja Bhagavathar / 🎼 Papanasam Sivan / 📝 Papanasam Sivan" },
{ file: "Vadhaname Chandra Bimbamo.mp3", details: "🎬 Sivakavi (1943) / 🎙️ M. K. Thyagaraja Bhagavathar / 🎼 Papanasam Sivan / 📝 Papanasam Sivan" },
{ file: "Vallalai Paadum Vaayal.mp3", details: "🎬 Sivakavi (1943) / 🎙️ M. K. Thyagaraja Bhagavathar / 🎼 Papanasam Sivan" },
{ file: "Vasantha Ruthu.mp3", details: "🎬 Sivakavi (1943) / 🎙️ M. K. Thyagaraja Bhagavathar, S. Jayalakshmi / 🎼 Papanasam Sivan / 📝 Papanasam Sivan" },
{ file: "Aagaya Vennilavae.mp3", details: "🎬 Arangetra Velai (1990) / 🎙️ K. J. Yesudas, Uma Ramanan / 🎼 Ilaiyaraaja / 📝 Vaali" },
{ file: "Pattu Poove.mp3", details: "🎬 Sembaruthi (1992) / 🎙️ S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali" },
{ file: "Nila Kayum Neram.mp3", details: "🎬 Sembaruthi (1992) / 🎙️ Mano, S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali" },
{ file: "Nadanthaal.mp3", details: "🎬 Sembaruthi (1992) / 🎙️ S. P. Balasubrahmanyam / 🎼 Ilaiyaraaja / 📝 Vaali" },
{ file: "Kadalile Thanimayil.mp3", details: "🎬 Sembaruthi (1992) / 🎙️ Nagoor Haniffa, Mano / 🎼 Ilaiyaraaja / 📝 Vaali" },
{ file: "Kadalile Ezhumpura.mp3", details: "🎬 Sembaruthi (1992) / 🎙️ Ilaiyaraaja / 🎼 Ilaiyaraaja / 📝 Vaali" },
{ file: "Chemparuthi Poovu.mp3", details: "🎬 Sembaruthi (1992) / 🎙️ Mano, K. S. Chithra, Dr. Bhanumathi / 🎼 Ilaiyaraaja / 📝 Vaali" },
{ file: "Chalakku Chalakku Selai.mp3", details: "🎬 Sembaruthi (1992) / 🎙️ Mano, S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali" },
{ file: "Boom shakala.mp3", details: "🎬 Kulir 100 Degrees (2015) / 🎙️ Bobo Shashi, Benny Dayal, Abishek & Nrithya / 🎼 Bobo Shashi / 📝 Pa. Vijay" },
{ file: "Ayyayo Nenju.mp3", details: "🎬 Aadukalam (2011) / 🎙️ G. V. Prakash Kumar, S. P. Balasubrahmanyam, S. P. B. Charan, Prashanthini / 🎼 G. V. Prakash Kumar / 📝 Snehan" },
{ file: "Otha Sollaala.mp3", details: "🎬 Aadukalam (2011) / 🎙️ G. V. Prakash Kumar, Velmurugan / 🎼 G. V. Prakash Kumar / 📝 Snehan" },
{ file: "Yathe Yathe.mp3", details: "🎬 Aadukalam (2011) / 🎙️ G. V. Prakash Kumar / 🎼 G. V. Prakash Kumar / 📝 Snehan" },
{ file: "Ponnu Oruthi Summa.mp3", details: "🎬 Charlie Chaplin (2002) / 🎙️ S. P. Balasubrahmanyam, Harish Ragavendra / 🎼 Bharani / 📝 Palani Bharathi" },
{ file: "Ava Kanna Partha.mp3", details: "🎬 Charlie Chaplin (2002) / 🎙️ S. P. Balasubrahmanyam, Harish Ragavendra / 🎼 Bharani / 📝 Palani Bharathi" },
{ file: "Muthalam Santhipil.mp3", details: "🎬 Charlie Chaplin (2002) / 🎙️ Swarnalatha, Unni Krishnan / 🎼 Bharani / 📝 Palani Bharathi" },
{ file: "Unthan Vizhi Munai.mp3", details: "🎬 4 Students (2004) / 🎙️ Jassie Gift, Jyotsna / 🎼 Jassie Gift / 📝 Palani Bharathi" },
{ file: "Lajjavathiyea.mp3", details: "🎬 4 Students (2004) / 🎙️ Jassie Gift / 🎼 Jassie Gift / 📝 Palani Bharathi" },
{ file: "Lajjavathiyea II.mp3", details: "🎬 4 Students (2004) / 🎙️ Jassie Gift / 🎼 Jassie Gift / 📝 Palani Bharathi" },
{ file: "Annakili II.mp3", details: "🎬 4 Students (2004) / 🎙️ Prasanna chorus / 🎼 Jassie Gift / 📝 Palani Bharathi" },
{ file: "Annakili.mp3", details: "🎬 4 Students (2004) / 🎙️ Jassie Gift / 🎼 Jassie Gift / 📝 Kaithapram" },
{ file: "Padagottum Pattamma.mp3", details: "🎬 Chinnavar (2020) / 🎙️ Malaysia Vasudevan, K. S. Chithra / 🎼 Ilaiyaraaja / 📝 Gangai Amaran" },
{ file: "Maaraappu Chela.mp3", details: "🎬 Chinnavar (2020) / 🎙️ Mano, K. S. Chithra / 🎼 Ilaiyaraaja / 📝 Gangai Amaran" },
{ file: "Kottukkili.mp3", details: "🎬 Chinnavar (2020) / 🎙️ K. S. Chithra, S. P. Balasubrahmanyam / 🎼 Ilaiyaraaja / 📝 Gangai Amaran" },
             { file: "Gunturu Gongura.mp3", details: "🎬 Chinnavar (2020) / 🎙️ Mano, K. S. Chithra / 🎼 Ilaiyaraaja / 📝 Gangai Amaran" },
         { file: "Paal Vannam.mp3", details: "🎬 Paasam (1962) / 🎤 P. B. Srinivas, P. Susheela / 🎼 Viswanathan - Ramamoorthy" },
             { file: "Andhiyiley Vaanam.mp3", details: "🎬 Chinnavar (2020) / 🎙️ Mano, Swarnalatha / 🎼 Ilayaraja / 📝 Gangai Amaran" },
             { file: "Kadavullum Neeyam.mp3", details: "🎬 Sindhu Nathi Poo (1994) / 🎙️ Unni Menon, S. Janaki / 🎼 Soundaryan / 📝 Vairamuthu" },
             { file: "Adiye Adi Chinnapulla.mp3", details: "🎬 Sindhu Nathi Poo (1994) / 🎙️ Mano, S. Janaki / 🎼 Soundaryan / 📝 Vairamuthu" },
             { file: "Mathalam Kottudhadi.mp3", details: "🎬 Sindhu Nathi Poo (1994) / 🎙️ S. P. Balasubrahmanyam, Swarnalatha, Loose Mohan / 🎼 Soundaryan / 📝 Vairamuthu" },
             { file: "Aathadi Enna Odambu.mp3", details: "🎬 Sindhu Nathi Poo (1994) / 🎙️ Shahul Hameed / 🎼 Soundaryan / 📝 Vairamuthu" },
             { file: "Aathi Vadayile.mp3", details: "🎬 Sindhu Nathi Poo (1994) / 🎙️ K. J. Yesudas / 🎼 Soundaryan / 📝 Vairamuthu" },
             { file: "Poi Vaada.mp3", details: "🎬 Dharmadurai (2016) / 🎙️ Srimathumitha / 🎼 Yuvan Shankar Raja / 📝 Vairamuthu" },
             { file: "Endha Pakkam.mp3", details: "🎬 Dharmadurai (2016) / 🎙️ Rahul Nambiar, Chinmayi Sripada / 🎼 Yuvan Shankar Raja / 📝 Vairamuthu" },
             { file: "Makka Kalanguthappa.mp3", details: "🎬 Dharmadurai (2016) / 🎙️ Mathichiyam Bala / 🎼 Yuvan Shankar Raja / 📝 Mathichiyam Bala" },
             { file: "Aandipatti.mp3", details: "🎬 Dharmadurai (2016) / 🎙️ Senthil Dass, Surmukhi / 🎼 Yuvan Shankar Raja / 📝 Vairamuthu" },
             { file: "Adi Raakkumuthu.mp3", details: "🎬 Ejamaan (1993) / 🎙️ S.P. Balasubrahmanyam / 🎼 Ilaiyaraaja / 📝 Vaali" },
     { file: "Ulagam Piranthathu.mp3", details: "🎬 Paasam (1962) / 🎤 T. M. Soundararajan / 🎼 Viswanathan - Ramamoorthy / 📝 Kannadasan" },
             { file: "Nilave Mugam.mp3", details: "🎬 Ejamaan (1993) / 🎙️ S. P. Balasubrahmanyam, S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali" },
             { file: "Oru Naalum Unai.mp3", details: "🎬 Ejamaan (1993) / 🎙️ S. P. Balasubrahmanyam, S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali" },
             { file: "Urakka Kaththu.mp3", details: "🎬 Ejamaan (1993) / 🎙️ S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali" },
 { file: "Poothathu_Poonthoppu.mp3", details: "🎬 Thanga Manasukkaran / 1992 /🎙️  Mano, S.Janaki /🎼  Ilaiyaraaja / 📝 Piraisoodan, Kamakodiyan, GangaiAmaran" },
             { file: "Aalappol_Velapol.mp3", details: "🎬 Ejamaan (1993) / 🎤 S.P. Balasubrahmanyam, Chithra / 🎼 Ilaiyaraaja / 📝 Vaali" },
   { file: "Peelings.mp3", details: "🎬 Pushpa 2 - The Rule ( Tamil) / 2024 /🎙️ Senthil Ganesh, Rajalakshmi /🎼 Devi Sri Prasad / 📝 Viveka, Siju Thuravoor" },
     { file: "Nee_Pottu_Vacha.mp3", details: "🎬 Ponmana Selvan (1989) / 🎤 Malaysia Vasudevan, Mano, K.S. Chithra / 🎼 Ilaiyaraaja / 📝 Gangai Amaran" },
      { file: "Naa_Ready.mp3", details: "🎬 Leo (2023) / 🎤 Thalapathy Vijay, Anirudh Ravichander / 🎼 Anirudh Ravichander / 📝 Vishnu Edavan" },
     { file: "Hey_Minnale.mp3", details: "🎬 Amaran (2024) / 🎤 Haricharan, Shweta Mohan / 🎼 G.V Prakash Kumar / 📝 Karthik Netha" },
     { file: "Achacho.mp3", details: "🎬 Aranmanai 4 (2024) / 🎤 Kharesma Ravichandran, Srinisha Jayaseelan, Hiphop Tamizha / 🎼 Hiphop Tamizha / 📝 Vignesh Srikanth" },
     { file: "Edho Solla.mp3", details: "🎬 Murungakkai Chips (2020) / 🎤 Sid Sriram / 🎼 Dharan Kumar / 📝 Ravindhar Chandrasekaran" },
      { file: "Chillanjirukkiye.mp3", details: "🎬 Lubber Pandhu (2024) / 🎤 Pradeep Kumar, Shivangi / 🎼 Sean Roldan / 📝 Mohan Rajan" }
    ]
  },

  {
    url: "https://github.com/atsuperman/PLAY/raw/main/",
    songs: [
     { file: "Beer_song_Pacha_Kuthikennen.mp3", details: "🎬 Diesel (2024) / 🎤 Gana Guna, Dhibu Ninan Thomas, Maniratnam, Kapil Kapilan / 🎼 Dhibu Ninan Thomas / 📝 Rokesh" },
     { file: "Kaattumalli.mp3", details: "🎬 Viduthalai Part 1 (2023) / 🎤 Ilaiyaraaja, Ananya Bhat / 🎼 Ilaiyaraaja / 📝 Ilaiyaraaja" }
    ]
  }
];

// Generate allSongs with encoded URLs
export const allSongs = repositories.flatMap(repo => 
  repo.songs.map(song => ({
    ...song,
    path: `${repo.url}${song.file}`.replace(/ /g, '%20') // Encode spaces
  }))
);
